# A configuration file for our Quality Infrastructure builds: https://wiki.gpii.net/w/Quality_Infrastructure

email: tony@raisingthefloor.org
env_runtime: linux-desktop

apps:
  - app_name: gpii-express
    git_repository: https://github.com/the-t-in-rtf/gpii-express.git
    git_branch: GPII-1985
    software_stack: nodejs
    software_stack_version: lts
    folder:
      dest: /app/gpii-express
    run_in: fedora
    deploy: false
    setup:
      - yarn install
    test_cmds:
      - yarn test
